version: "3.7"

services:
  front:
    image: node:16.17-alpine
    command: sh -c "npm install && npm run dev"
    working_dir: /app
    ports:
      - 3000:3000
    volumes:
      - ./front:/app
    depends_on:
      - php

  php:
    build:
      context: .
      dockerfile: app-php.dockerfile
    working_dir: /var/www
    volumes:
      - ./back:/var/www
    ports:
      - 9000:9000
    depends_on:
      - mysql

  nginx:
    build:
      context: .
      dockerfile: app-nginx.dockerfile
    working_dir: /var/www
    volumes:
      - ./back:/var/www
    ports:
      - 80:80
    depends_on:
      - php

  mysql:
    image: mysql/mysql-server:8.0
    ports:
      - '3306:3306'
    volumes:
       - todo-mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_HOST: '%'
      MYSQL_USER: test
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: laravel

volumes:
  todo-mysql-data: